version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: account_db
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  api:
    build: 
      context: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '${PORT:-3000}:3000'
    restart: always

