version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: evaluation_db
    ports: 
      - ${PORT}:${PORT}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}