version: '3.7'

services:

  db:
    image: postgres:latest
    container_name: evaluation_db
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U evaluation -d evaluation_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: 
      context: .
    container_name: evaluation_ms
    ports:
      - '${PORT:-8080}:8080'
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/evaluation_db
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_DEFER-DATASOURCE-INITIALIZATION: true
      SPRING_SQL_INIT_MODE: always