version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: account_db
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}